# Default configuration

attn_head_set: "22-4,15-18,19-15,14-7,17-18,14-0,16-13,16-20,22-22,19-22,16-0,19-20,26-25,14-4,23-13,22-6" # top16
model_base_class: "Qwen2.5-7B-Instruct"
model_name_or_path: "Qwen/Qwen2.5-7B-Instruct"