# Default configuration

attn_head_set: "9-10,11-11,9-13,16-1,12-2,11-13,20-7,12-12,9-8,21-12,16-4,11-5,16-6,12-10,5-6,11-8"
model_base_class: "Qwen2-0.5B-Instruct"
model_name_or_path: "Qwen/Qwen2-0.5B-Instruct"